57 unscanned tag is constantly deleted
GDATASoftwareAG/nextcloud-gdata-antivirus pull request #71
Opened 2024-07-03 10:51 UTC by unglaublicherdude

This PR does now a number of things.

1. It fixes both tag problems

     1. The Unscanned tag will not be created constantly, because the ScanService will not create it constantly anymore
     2. The TagService will now not just remove all tags from files it will tag, it will lookup the tags for a file and just create and delete what's needed

2. Adding unittest

I addes some tests run by phpunit as we already have in the vaas-sdk. You can take these tests as example, to add your own tests.

3. Adding some devcontainer features

The most important one is the docker-in-docker feature. This means you can now run everything within the devcontainer. So you start the devcontainer, run the ./install.sh script and it will run nextcloud within the devcontainer.  Meaning to go to the nextcloud page running in this container, you can just click on the browser-icon in the ports tab in your vscode.

![image](https://github.com/GDATASoftwareAG/nextcloud-gdata-antivirus/assets/13208176/1b85b614-cbec-444c-a117-c8a254b3df1b)

5. overriding a dependency of webpack-vue-config as it has a vulnerability marked as high 

```json
  "overrides": {
    "@nextcloud/webpack-vue-config": {
      "webpack-dev-server": "5.0.4"
    }
  }
```

2024-07-08 06:31 UTC, pstadermann requested changes
Currently removes all other tags when setting. I thought we should only remove our tags.

2024-07-08 06:31 UTC, pstadermann commented on lib/Command/GetTagIdCommand.php
> +		$this->setDescription('tags all files without tag from this app as unscanned');
Description does not match function. Maybe "Gets the ID of a tag".

2024-07-08 06:31 UTC, pstadermann commented on lib/Command/RemoveTagCommand.php
> +		$this->setDescription('tags all files without tag from this app as unscanned');
```suggestion
		$this->setDescription('deletes a tag');
```

2024-07-08 06:31 UTC, pstadermann commented on lib/Command/RemoveTagCommand.php
> +		$this->addArgument(self::TAG_NAME, InputArgument::REQUIRED, "Tag name want to delete.");
```suggestion
		$this->addArgument(self::TAG_NAME, InputArgument::REQUIRED, "The name of the tag name you want to delete.");
```

2024-07-08 06:31 UTC, pstadermann commented on lib/Service/TagService.php
> +					$this->tagMapper->unassignTags(strval($fileId), 'files', [$tagId]);
Doesn't this remove all tags, not only ours?

2024-07-08 17:07 UTC, lennartdohmann requested changes

2024-07-08 17:07 UTC, lennartdohmann commented on lib/Command/RemoveTagCommand.php
> +		$this->setDescription('tags all files without tag from this app as unscanned');
Same here

2024-07-10 12:17 UTC, doxthree approved these changes

2024-07-11 07:25 UTC, lennartdohmann approved these changes

2024-07-11 07:38 UTC, lennartdohmann commented on tests/unittests/TagServiceTest.php
> +					$this->assertEquals($tagIds, [TagService::CLEAN]);
The assertions are misordered. The actual value should be second.
![Screenshot 2024-07-11 093658](https://github.com/GDATASoftwareAG/nextcloud-gdata-antivirus/assets/99874374/6da27d5e-d53c-432b-862d-dd0b0319f354)

2024-07-11 07:41 UTC, lennartdohmann commented on lib/Command/GetTagIdCommand.php
> +		} catch (TagNotFoundException $e) {
I run into issues because this is not imported.

2024-07-11 07:41 UTC, lennartdohmann commented on lib/Command/GetTagIdCommand.php
> +use OCA\GDataVaas\Service\TagService;
```suggestion
use OCP\SystemTag\TagNotFoundException;
```

2024-07-11 07:42 UTC, lennartdohmann commented on lib/Command/GetTagIdCommand.php
> +	protected function configure() {
```suggestion
	protected function configure(): void {
```

2024-07-11 08:02 UTC, lennartdohmann commented
@unglaublicherdude I opened [this PR](https://github.com/GDATASoftwareAG/nextcloud-gdata-antivirus/pull/76) into this with my suggestions.

2024-07-11 09:34 UTC, pstadermann approved these changes

2024-07-11 10:29 UTC, merged